# Generated by Django 4.2.7 on 2024-01-14 23:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dash', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BkoReprovado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bko_reprovado', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'BKO Reprovado',
                'verbose_name_plural': 'BKO Reprovados',
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cargo', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
            },
        ),
        migrations.CreateModel(
            name='Consultor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Consultor',
                'verbose_name_plural': 'Consultores',
            },
        ),
        migrations.CreateModel(
            name='Credito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credito', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Crédito',
                'verbose_name_plural': 'Créditos',
            },
        ),
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('equipe', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Equipe',
                'verbose_name_plural': 'Equipes',
            },
        ),
        migrations.CreateModel(
            name='FamiliaProduto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('familia_produto', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Familia Produto',
                'verbose_name_plural': 'Familia Produtos',
            },
        ),
        migrations.CreateModel(
            name='MotivoCancelamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo_cancelamento', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Motivo Cancelamento',
                'verbose_name_plural': 'Motivo Cancelamento',
            },
        ),
        migrations.CreateModel(
            name='Observacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacao', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Observação',
                'verbose_name_plural': 'Observações',
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('produto', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
        migrations.CreateModel(
            name='TipoAgenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_agenda', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Tipo Agenda',
                'verbose_name_plural': 'Tipo Agenda',
            },
        ),
        migrations.CreateModel(
            name='TipoOferta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('oferta', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Oferta',
                'verbose_name_plural': 'Ofertas',
            },
        ),
        migrations.CreateModel(
            name='TipoPN',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_PN', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'PN',
                'verbose_name_plural': 'PN',
            },
        ),
        migrations.CreateModel(
            name='Uf',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uf', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'UF',
                'verbose_name_plural': 'UF',
            },
        ),
        migrations.CreateModel(
            name='DadosPedidosDeletados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_exclusao', models.DateTimeField(auto_now_add=True)),
                ('carimbo_data_hora', models.DateTimeField()),
                ('consultor', models.CharField(blank=True, max_length=255, null=True)),
                ('data', models.DateField(blank=True, null=True)),
                ('atividade', models.IntegerField(blank=True, null=True)),
                ('cnpj', models.CharField(blank=True, max_length=20, null=True)),
                ('razao_social', models.CharField(blank=True, max_length=255, null=True)),
                ('qtd', models.IntegerField(blank=True, null=True)),
                ('valor', models.FloatField(blank=True, null=True)),
                ('simulacao', models.IntegerField(blank=True, null=True)),
                ('cotacao', models.CharField(blank=True, max_length=100, null=True)),
                ('pedido', models.CharField(blank=True, max_length=255, null=True)),
                ('data_ativacao', models.DateField(blank=True, null=True)),
                ('data_agenda', models.DateField(blank=True, null=True)),
                ('hora_agenda', models.TimeField(blank=True, null=True)),
                ('data_campanha', models.DateField(blank=True, null=True)),
                ('nome_gestor', models.CharField(blank=True, max_length=255, null=True)),
                ('celular_gestor', models.CharField(blank=True, max_length=20, null=True)),
                ('email_gestor', models.EmailField(blank=True, max_length=255, null=True)),
                ('data_cqv', models.DateField(blank=True, null=True)),
                ('bko_cqv', models.CharField(blank=True, max_length=255, null=True)),
                ('data_criacao', models.DateField(blank=True, null=True)),
                ('bko_criacao', models.CharField(blank=True, max_length=255, null=True)),
                ('data_aceite', models.DateField(blank=True, null=True)),
                ('bko_aceite', models.CharField(blank=True, max_length=255, null=True)),
                ('data_input', models.DateField(blank=True, null=True)),
                ('bko_input', models.CharField(blank=True, max_length=255, null=True)),
                ('data_pn_salvo', models.DateField(blank=True, null=True)),
                ('pn_salvo', models.CharField(blank=True, max_length=255, null=True)),
                ('login_usuario', models.CharField(blank=True, max_length=255, null=True)),
                ('email_usuario', models.EmailField(blank=True, max_length=255, null=True)),
                ('data_hora_atualizado_status', models.DateTimeField(blank=True, null=True)),
                ('bko_reprovado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bko_rep_delete', to='pedidos.bkoreprovado')),
                ('campanha', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='oferta_pk_delete', to='pedidos.tipooferta')),
                ('cargo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cargo_fk_delete', to='pedidos.cargo')),
                ('credito', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pedidos.credito')),
                ('equipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipe_fk_delete', to='pedidos.equipe')),
                ('familia_produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='familia_produto_fk_delete', to='pedidos.familiaproduto')),
                ('motivo_cancelamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pedidos.motivocancelamento')),
                ('observacao_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='obs_1_delete', to='pedidos.observacao')),
                ('observacao_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='obs_2_delete', to='pedidos.observacao')),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='produto_pk_delete', to='pedidos.produto')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_delete', to='dash.descricaostatus')),
                ('status_pn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='status_pn_delete', to='pedidos.tipopn')),
                ('tipo_agenda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tip_agenda_delete', to='pedidos.tipoagenda')),
                ('uf', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uf_fk_delete', to='pedidos.uf')),
            ],
            options={
                'verbose_name': 'Pedido Deletado',
                'verbose_name_plural': 'Pedidos Deletados',
            },
        ),
        migrations.CreateModel(
            name='DadosPedidos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('carimbo_data_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('consultor', models.CharField(blank=True, max_length=255, null=True)),
                ('data', models.DateField(blank=True, null=True)),
                ('atividade', models.IntegerField(blank=True, null=True)),
                ('cnpj', models.CharField(blank=True, max_length=20, null=True)),
                ('razao_social', models.CharField(blank=True, max_length=255, null=True)),
                ('qtd', models.IntegerField(blank=True, null=True)),
                ('valor', models.FloatField(blank=True, null=True)),
                ('simulacao', models.IntegerField(blank=True, null=True)),
                ('cotacao', models.CharField(blank=True, max_length=100, null=True)),
                ('pedido', models.CharField(blank=True, max_length=255, null=True)),
                ('data_ativacao', models.DateField(blank=True, null=True)),
                ('data_agenda', models.DateField(blank=True, null=True)),
                ('hora_agenda', models.TimeField(blank=True, null=True)),
                ('data_campanha', models.DateField(blank=True, null=True)),
                ('nome_gestor', models.CharField(blank=True, max_length=255, null=True)),
                ('celular_gestor', models.CharField(blank=True, max_length=20, null=True)),
                ('email_gestor', models.EmailField(blank=True, max_length=255, null=True)),
                ('data_cqv', models.DateField(blank=True, null=True)),
                ('bko_cqv', models.CharField(blank=True, max_length=255, null=True)),
                ('data_criacao', models.DateField(blank=True, null=True)),
                ('bko_criacao', models.CharField(blank=True, max_length=255, null=True)),
                ('data_aceite', models.DateField(blank=True, null=True)),
                ('bko_aceite', models.CharField(blank=True, max_length=255, null=True)),
                ('data_input', models.DateField(blank=True, null=True)),
                ('bko_input', models.CharField(blank=True, max_length=255, null=True)),
                ('data_pn_salvo', models.DateField(blank=True, null=True)),
                ('pn_salvo', models.CharField(blank=True, max_length=255, null=True)),
                ('login_usuario', models.CharField(blank=True, max_length=255, null=True)),
                ('email_usuario', models.EmailField(blank=True, max_length=255, null=True)),
                ('data_hora_atualizado_status', models.DateTimeField(blank=True, null=True)),
                ('bko_reprovado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bko_rep', to='pedidos.bkoreprovado')),
                ('campanha', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='oferta_pk', to='pedidos.tipooferta')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cargo_fk', to='pedidos.cargo')),
                ('credito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.credito')),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipe_fk', to='pedidos.equipe')),
                ('familia_produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='familia_produto_fk', to='pedidos.familiaproduto')),
                ('motivo_cancelamento', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pedidos.motivocancelamento')),
                ('observacao_1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='obs_1', to='pedidos.observacao')),
                ('observacao_2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='obs_2', to='pedidos.observacao')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produto_pk', to='pedidos.produto')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status', to='dash.descricaostatus')),
                ('status_pn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='status_pn', to='pedidos.tipopn')),
                ('tipo_agenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tip_agenda', to='pedidos.tipoagenda')),
                ('uf', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uf_fk', to='pedidos.uf')),
            ],
            options={
                'verbose_name': 'Dado Pedido',
                'verbose_name_plural': 'Dado Pedidos',
            },
        ),
    ]
