# Generated by Django 4.2.7 on 2024-01-14 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='DescricaoStatus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descricao_status', models.CharField(max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Descrição Status',
                'verbose_name_plural': 'Descrição Status',
            },
        ),
        migrations.CreateModel(
            name='DescricaoTipo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descricao_tipo', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UrlDashBoard',
            fields=[
                ('id_url', models.AutoField(primary_key=True, serialize=False)),
                ('nome_dash', models.CharField(blank=True, max_length=255, verbose_name='Titulo')),
                ('url', models.URLField(max_length=2048)),
                ('group', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
            ],
            options={
                'verbose_name': 'Indicador',
                'verbose_name_plural': 'Indicadores',
            },
        ),
        migrations.CreateModel(
            name='DeparaDashBoard',
            fields=[
                ('id_depara', models.AutoField(primary_key=True, serialize=False)),
                ('ativo', models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], default='S', max_length=3, null=True)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_pk', to='dash.descricaostatus')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tipo_pk', to='dash.descricaotipo')),
            ],
        ),
    ]
